### PR TITLE
fix typo in Query Configs docs

### PR DESCRIPTION
**Pull request by willcaul**

### CODE REVIEW

**Comment by kelvin-lu** [comment]
Thank you for your vigilance! :)

**Comment by willcaul** [comment]
> Thank you for your vigilance! :)

No problem! :)

**Comment by willcaul** [comment]
> Thank you for your vigilance! :)

@kelvin-lu - will the updated docs get deployed automatically or does someone at amplitude need to publish them?

**Comment by rctbusk** [comment]
Sorry about that! Should be updated now!

**Comment by willcaul** [comment]
> Sorry about that! Should be updated now!

Thanks @rctbusk!

**Pull request merged**
