### PR TITLE
Promisified forceRequest + connect-request tests

### PR DESCRIPTION
**Pull request by karevn**

### CODE REVIEW

**Comment by ryanashcraft** [comment]
I haven't thoroughly reviewed this, but want to share some early feedback and thoughts:

- Please don't check in package-lock.json and use yarn for adding dependencies.
- Please resolve the conflicts with package.json. This should allow us to fully test the build on Travis.
- I'm not 100% sure if returning an array of promises makes sense. Unless we pass metadata about which query belongs at which index, I don't know how an flat array of promises would be more useful than a single promise. Does that make sense?

**Comment by karevn** [comment]
Done regarding the conflicts and package-lock.json
On the promises - it's a very good point. I'll think about adding metadata to make it more useful. Or may be convert to just `Promise.all`

**Comment by ryanashcraft** [comment]
@karevn I think I'm leaning towards a single Promise as its simpler and will be easier for new users of the library to understand. There's always a workaround if you need more complicated behavior by manually dispatch `requestAsync` actions.

**Comment by karevn** [comment]
@ryanashcraft there's also an interesting question. What happens if the next scenario will take place:
1. Component has mounted and requested all the data. Let's say, prop `foo` is used as request param.
2. We call `forceRequest`, get the promise and that request takes some long time, like 10 sec.
3. `foo` prop changes and triggers yet another request.
Question: should the promise resolve when step 2's request is finished, or should it resolve when step 3's request is finished?

**Comment by ryanashcraft** [comment]
@karevn Interesting question. My first thought is it should just be the same promise we get from dispatching that forceRequest query. I wouldn't expect the promise to be a signal for any other request than the one that was triggered by that specific function invocation.

It's interesting though because we'd probably cancel the query from the forceRequest when this happens, and I think with the default superagent interface we don't ever trigger an end callback and resulting promise rejection. This is not great. Probably should fix up the superagent interface to properly call the callback function whenever the request is aborted.

**Comment by karevn** [comment]
Have you had a look at my latest commits? I've come to the conclusion it's quite simple: when you call `forceRequest`, you just return a promise which is resolved when all the pending requests are resolved one way or another. It's quite intuitive. The only concern that I have - what's with error handling...

**Comment by ryanashcraft** [comment]
@karevn I think part of the problem here is that `forceRequest` does not have well-defined use cases or any specs. We only use it in a handful of places in our codebase. I think ideally we would evaluate all of the real-life use cases for this API and create clear specs around its behavior – which could possible mean splitting `forceRequest` up into multiple APIs and deprecating `forceRequest`.

In the interim… I have reservations with having `forceRequest` resolve when all requests are finished. I'd still prefer to have it return an array result from `Promise.all` with all of the accompanying result data (response body, response headers, status, etc.). This will help handle cases where you would like to easily grab the response data from the `forceRequest` promise. Do you have specific use cases that would not be covered by this approach?

**Comment by karevn** [comment]
For me, there are the next use cases:
1. something like promisified `fetchData` function is required for SSR (which is on it's way). Just returning an empty promise should be enough.
2. Reloading some front-end data upon user requests ("click to refresh").
3. My project uses it for polling (even though polling is not  a good idea per se, but I'm limited by the backend design).
It looks like `fetchData({force: true}): Promise` should be good enough for all of these cases.

**Comment by ryanashcraft** [comment]
Going forward, I'd like to focus attention on the hooks API and just keep connectRequest's API as-is. I was never happy with the different options we discussed here. I think the issue resolved mostly over figuring out how to handle the fact that connectRequest can accept multiple queryConfigs. With hooks API, we're going to require one hook instance per-request. This way we can easily add some sort of API for getting metadata about that particular query.

See #129 for the initial hooks API. Happy to hear feedback.

Other notes:
- For SSR, I'd encourage publishing your own package that builds on top of redux-query and redux-query-react for this.
- #129 adds new tests for connectRequests and new hooks.
- In the future, I think it'd be easier for everyone to discuss API changes in an issue before anyone starts coding.

**Pull request closed without merging**
