### PR TITLE
Add little blurb about mapPropsToConfig

### PR DESCRIPTION
**Pull request by MrNice**
There was a question about multiple requests so I added this blurb.

### CODE REVIEW

**Comment by MrNice** [comment]
@bstro Would this change have enabled you to get to work without asking a question?

**Comment by mutewinter** [comment]
This blurb helped me! Didn't realize it was possible to make multiple requests. Also, I like the name of the abstraction `mapPropsToConfig`, really easy to remember.

**Comment by MrNice** [comment]
Sweet! Yeah it's in the source code which is where I adopted the name from.

On Mar 23, 2017 2:16 PM, "Jeremy Mack" <notifications@github.com> wrote:

This blurb helped me! Didn't realize it was possible to make multiple
requests. Also, I like the name of the abstraction mapPropsToConfig, really
easy to remember.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amplitude/redux-query/pull/41#issuecomment-288862780>,
or mute the thread

**Comment by rogovdm** [comment]
Thanks :)

**Comment by ryanashcraft** [comment]
@MrNice Can you update the examples to use the name `mapPropsToConfig` instead of the anonymous arrow functions. This will help people connect the explanations to the code. Also, the last sentence is confusing to me and not sure if it's really worth bringing up. Other than that looks good.

**Comment by bstro** [comment]
Yup, this would have helped, @MrNice 
Thanks!!

**Comment by MrNice** [comment]
@ryanashcraft I updated the examples to match what I use in production, but tried to match your coding style.

Sorry about the confusing sentence - there's a way I compose arrays of configs and flatten them at the end that's horribly inefficient that this alluded to:
```js
connectRequest(props => _.flattenDeep([requests.dashboard(props.dashboardId || 12),
                                                                     requests.getUserDetails(props.users || [1, 2, 3, 4])]))

// where                                     returns
getUserDetails([1, 2, 3, 4]) => [config1, config2, config3, config4]
```

**Comment by MrNice** [comment]
@ryanashcraft This look good to you?

**Comment by ryanashcraft** [comment]
@MrNice I prefer the original version (without the last sentence). I don't want the examples in the README to get too complicated; want them to be super simple and introduce as few concepts as possible. When we graduate to having more robust documentation, I think it makes sense to tackle these sorts of usage patterns.

**Comment by ryanashcraft** [comment]
Hey @MrNice. I've (finally) updated the README to mention `mapPropsToConfigs` and go into more detail about how `connectRequest` works and recommending using `redux`'s `compose`. Thanks for bringing this issue up and collaborating.

**Pull request closed without merging**
