### PR TITLE
Support react-redux 6 with reduxContext option

### PR DESCRIPTION
**Pull request by philip-peterson**
Hey Ryan. This PR should resolve issue #124.

### CODE REVIEW

**Comment by justanotherjones** [comment]
:wave: thanks for the PR!

**Comment by preactive** [comment]
@ryanashcraft when merged when will this hit npm?

**Comment by ryanashcraft** [comment]
@preactive Yes we'll ship this to npm when we get the chance to review and test. ETA sometime this week.

**Comment by preactive** [comment]
Awesome sauce!  thanks @ryanashcraft!

**Comment by ManThursday** [comment]
Hey @philip-peterson,

Thanks for the PR!

Sorry it's taken us a bit of time to review it. After taking a look there are a couple of changes we'd like to propose/discuss.

1. We think it will make the code cleaner to make this a backwards incompatible change and cut a new major version of redux-query that depends on react-redux 6+.
2. How would you feel about breaking this PR down into two separate stages?
One PR for the react-redux 6 compatibility just using the default `ReactReduxContext`.
And another PR for the custom store context API.
I think @ryanashcraft would like to have a longer think about the custom store API change. But we don't want that to be a blocker for the first part.

Let us know what you think.

And if you don't have time to work on this anymore we'd be happy to pick it up from where you left it.

**Comment by philip-peterson** [comment]
Hey Amplitude peeps,

Those sound like reasonable changes. Only thing is to be wary of is people using this library on older installations of react-redux who may start asking for backports to bugfixes. Personally I'm not in that situation but we were only just recently able to upgrade our react-redux version, and React 15 obviously doesn't have the new context API.

Likely won't have a whole lot of bandwidth these coming weeks (things are pretty busy), so it would be best if y'all could pick this up.

Thanks <3

**Comment by ManThursday** [comment]
> Only thing is to be wary of is people using this library on older installations of react-redux who may start asking for backports to bugfixes.

Yep, that's a good point.

We're not currently planning any other major changes so hopefully this won't come up. If it does then we can always consider adding back backwards compatibility.

**Comment by ManThursday** [comment]
Hey @philip-peterson,

Sorry that I didn't get to this sooner. I spent a bit of time this weekend working on the first stage of our proposed changes - making redux-query depend on the default `ReactReduxContext`.

Unfortunately I haven't been able to get that figured out. Given the current state of react-redux (https://github.com/reduxjs/react-redux/issues/1177) I don't think I'm going to invest any more time in attempting this upgrade.

@preactive if you need support for react-redux 6 right now I'd suggest using @philip-peterson's branch for now.

When the "fixed" react-redux 6, or react-redux 7 comes out we'll revisit this.

**Comment by preactive** [comment]
@ManThursday Thanks for the update and info!

**Comment by salvoravida** [comment]
you shouldtry this https://github.com/salvoravida/react-redux-fork 6.5.0 

reading from <ReactReduxContext.Consumer > is very slow.
Regards

**Comment by jesnil01** [comment]
react-redux 7 is now out

**Comment by ryanashcraft** [comment]
Closing this in favor of #129. Thanks again @philip-peterson for the initial implementation.

**Pull request closed without merging**
