### PR TITLE
Allow setting headers

### PR DESCRIPTION
**Pull request by adamsanderson**
Addresses #3 by allowing users to set `options.headers` in `connectRequest`.

### CODE REVIEW

**Comment by ryanashcraft** [comment]
This looks great! Thanks for adding a test and update the README. Seems `npm run lint` is complaining, though.

I'm currently on vacation so I will have to take another look when I get back.

**Comment by adamsanderson** [comment]
Oh OK, I didn't notice you had that set up. I'll run it and fix whatever
needs fixing. Enjoy your vacation, and stop checking github ;)

**Comment by ryanashcraft** [comment]
@adamsanderson Can you modify the `MUTATE_ASYNC` case in the query middleware to set the headers for mutations? And it'd be great if you could add an accompanying test for mutations in `query.tests.js`. Thanks!

**Comment by adamsanderson** [comment]
Sure, no problem.  For one reason or another I assumed that the both the mutations and the query branches shared the same request configuration code and didn't look closely enough.  This should do the trick.

**Comment by ryanashcraft** [comment]
@adamsanderson Thanks for this change!

**Pull request merged**
