### PR TITLE
Store request controller, rather than its instance

### LINKED ISSUE #68: Abortion is not being performed on the controller
Request controllers (as returned by network adapters) expose an `abort` method which is supposed to be used to interrupt the underlying request. See [`superagent` adapter](https://github.com/amplitude/redux-query/blob/master/src/adapters/superagent.js#L43) for an example.

However, since the addition of the `instance` prop (e4b33fb) this controller is no longer stored in the state, and instead [its `instance` is](https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L112). 

This causes the middleware to [call `.abort()` on the wrong object](https://github.com/amplitude/redux-query/blob/master/src/middleware/query-advanced.js#L278).

### PR DESCRIPTION
**Pull request by acontreras89**
Fix #68.

### CODE REVIEW

**Comment by acontreras89** [comment]
You may want to rename the property to `controller` (rather than `request`) to avoid confusion.

**Comment by ryanashcraft** [comment]
@acontreras89 Good catch. Putting this on the 2.0 branch we're tracking to release along with a few breaking changes.

**Comment by acontreras89** [comment]
I found this bug while testing [fetch adapter](https://www.npmjs.com/package/fetch-adapter) :) I told you about it in some other issue, and it has finally made it to npm.

@ryanashcraft I've been wanting to ask, is there any other channel to get in touch with you (`redux-query` maintainers) besides this repo? Perhaps a gitter/slack/discord community?

I've been spending quite some time with your library lately, and I'd love to share some of my thoughts with you in a more direct manner.

Also, is there any info on the breaking changes that 2.0 will introduce?

**Comment by ryanashcraft** [comment]
@acontreras89 For now I want to keep everything in Github as my time is pretty stretched and don't want to set expectations that I can't fulfill. Also lets other contributors chime in when appropriate.

If you have ideas, please create an issue(s). I've also made a 2.0 issue for open discussion:
 https://github.com/amplitude/redux-query/issues/70.

**Pull request merged**
