### PR TITLE
Add headers to return

### PR DESCRIPTION
**Pull request by jnutter**
Return headers to promise resolve.

Use case: When fetching pagination data, our API returns a next page header.

### CODE REVIEW

**Comment by jnutter** [comment]
Do you think its better to return the whole response instead? I would like the response.ok as well as err.

**Comment by ryanashcraft** [comment]
@jnutter You'll need to update this PR because of the changes from #23.

Let's call the field `headers` when supplied to the promise callback. Additionally, can you also go ahead and start including it in the REQUEST_SUCCESS / REQUEST_FAILURE / MUTATE_SUCCESS / MUTATE_FAILURE actions with the field name `responseHeaders`? See #39 for a reference here.

I want to avoid passing variables that are too specific to superagent. You should be ok (pun intended 😝) with computing `ok` from `status` in your app. See the "Response status" section in [superagent's docs](https://visionmedia.github.io/superagent/#response-properties) for how it computes `response.ok`.

**Comment by jnutter** [comment]
@ryanashcraft please let me know if there is anything else 😄

**Comment by ryanashcraft** [comment]
thanks for contributing again @jnutter!

**Pull request merged**
